modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="Project ReDev" #mandatory
description='''

'''

[[mixins]]
config="redev.mixins.json"

[[accessTransformers]]
file="META-INF/redev_at.cfg"

[[dependencies.${mod_id}]] #optional
   modId="neoforge" #mandatory
   mandatory=true #mandatory
   versionRange="${neo_version_range}" #mandatory
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
